title: "Naz Mohammed Agh-Atabay"
description: "Academic website of Professor Naz Mohammed Agh-Atabay"

url: "https://ourapteryx514.github.io"
baseurl: "/atabay"

theme: minima

header_pages:
  - index.md
  - about.md
  - research.md
  - publications.md
  - teaching.md
  - interests.md
  - contact.md
